{"name": "Тест получения заказа пользователя без авторизации", "status": "passed", "description": "Получение ошибки при попытке получить инфо о заказе без авторизации", "start": 1727882465008, "stop": 1727882465807, "uuid": "0b73dec6-bdb9-4048-90d2-f0b0842fee58", "historyId": "dc6b5b7f88d5637c7c3efcd603b1dc6b", "testCaseId": "dc6b5b7f88d5637c7c3efcd603b1dc6b", "fullName": "tests.test_api_get_user_orders.TestApiGetUserOrders#test_no_auth_user_get_user_order_error", "labels": [{"name": "feature", "value": "Проверка получения заказа конкретного пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_get_user_orders"}, {"name": "subSuite", "value": "TestApiGetUserOrders"}, {"name": "host", "value": "DESKTOP-E2MLG10"}, {"name": "thread", "value": "14732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_get_user_orders"}]}