{"name": "Тест авторизации существующего пользователя", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "@pytest.fixture\n    def user_data_and_token():\n        payload = helpers.payload\n        response = requests.post(UrlsConstants.CREATE_USER, data=payload)\n>       token = response.json()['accessToken']\nE       KeyError: 'accessToken'\n\ntests\\conftest.py:11: KeyError"}, "description": "Успешная авторизация пользователя", "start": 1727882465811, "stop": 1727882465811, "uuid": "29ecae1c-e430-4d04-b55c-9e3d0808688a", "historyId": "c7cfb498f496fb29d05b8fc69edeee15", "testCaseId": "c7cfb498f496fb29d05b8fc69edeee15", "fullName": "tests.test_api_login_user.TestLoginUser#test_login_existing_user_successful", "labels": [{"name": "feature", "value": "Проверка авторизации пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-E2MLG10"}, {"name": "thread", "value": "14732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_login_user"}]}